"""Initial migration

Revision ID: 2d3a52c3445c
Revises: 
Create Date: 2024-06-28 17:44:59.117732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2d3a52c3445c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('emp', 'emp_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               autoincrement=True)
    op.drop_column('emp', 'emp_name')
    op.drop_column('emp', 'manager_id')
    op.drop_column('emp', 'emp_age')
    op.drop_column('emp', 'salary')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emp', sa.Column('salary', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('emp', sa.Column('emp_age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('emp', sa.Column('manager_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('emp', sa.Column('emp_name', mysql.VARCHAR(length=20), nullable=True))
    op.alter_column('emp', 'emp_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               autoincrement=True)
    # ### end Alembic commands ###
